# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x08tutorial\x1a google/protobuf/field_mask.proto\"=\n\x08Response\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\t\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\t\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\t\"l\n\x07Request\x12\x0f\n\x07\x66ield_1\x18\x01 \x01(\t\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\t\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\t\x12.\n\nfield_mask\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.FieldMask2C\n\x06Sample\x12\x39\n\x0eSampleFunction\x12\x11.tutorial.Request\x1a\x12.tutorial.Response\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=60
  _RESPONSE._serialized_end=121
  _REQUEST._serialized_start=123
  _REQUEST._serialized_end=231
  _SAMPLE._serialized_start=233
  _SAMPLE._serialized_end=300
# @@protoc_insertion_point(module_scope)
