# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sample_pb2 as sample__pb2


class SampleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleFunction = channel.unary_unary(
                '/tutorial.Sample/SampleFunction',
                request_serializer=sample__pb2.Request.SerializeToString,
                response_deserializer=sample__pb2.Response.FromString,
                )


class SampleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SampleFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleFunction,
                    request_deserializer=sample__pb2.Request.FromString,
                    response_serializer=sample__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tutorial.Sample', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sample(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SampleFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tutorial.Sample/SampleFunction',
            sample__pb2.Request.SerializeToString,
            sample__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
